- ignore: { name: "Use <$>" }
- ignore: { name: "Use ++" }
- ignore: { name: "Use unless" }
- ignore: { name: "Use newtype instead of data" }
- ignore: { name: "Reduce duplication" }
- ignore: 
    name: "Redundant pure"
    within: AMQP.Serialisation.Frame.parseHeartbeatFrame
- ignore:
    name: "Redundant bracket"
    within: 
      - AMQP.Serialisation.Generated.Methods
      - AMQP.Serialisation.Generated.Content
