- ignore: { name: "Use <$>" }
- ignore: { name: "Use unless" }
- ignore: { name: "Use newtype instead of data" }
- ignore:
    name: "Redundant bracket"
    within: 
      - AMQP.Serialisation.Generated
