resolver: lts-16.31
packages:
- amqp-generator
- amqp-serialisation
- amqp-serialisation-gen
- amqp-client
extra-deps:
- github: NorfairKing/sydtest
  commit: 83685ec68c3c167503ba8aee44000f2d8bb43a07
  subdirs:
  - sydtest
  - sydtest-discover
  - sydtest-rabbitmq
  - sydtest-typed-process
- github: NorfairKing/yamlparse-applicative
  commit: 7a329d06ffa45595963cf98f34910887115eb471
  subdirs:
  - yamlparse-applicative
- github: NorfairKing/safe-coloured-text
  commit: 2e61b50dfa65bed862aff903f574175cfc747e14
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-terminfo
- envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842
- github: NorfairKing/validity
  commit: 86a824729519c154c23f0757f2ce4b9ab93b675a
  subdirs:
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-hspec-binary
    - genvalidity-hspec-cereal
    - genvalidity-hspec-hashable
    - genvalidity-hspec-optics
    - genvalidity-hspec-persistent
    - genvalidity-path
    - genvalidity-persistent
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-hashable
    - genvalidity-sydtest-lens
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-containers
    - validity-path
    - validity-persistent
    - validity-primitive
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector

nix:
  shell-file: shell.nix
