resolver: lts-16.31
packages:
- amqp-generator
- amqp-serialisation
- /home/syd/src/sydtest/sydtest
- /home/syd/src/sydtest/sydtest-discover
extra-deps:
    # - github: NorfairKing/sydtest
    #   commit: 71f4421ca6d17300fcbceb1d6407eabd7e6086e3
    #   subdirs:
    #   - sydtest
    #   - sydtest-discover
    #   - sydtest-typed-process
- github: NorfairKing/yamlparse-applicative
  commit: 7a329d06ffa45595963cf98f34910887115eb471
  subdirs:
  - yamlparse-applicative
- github: NorfairKing/safe-coloured-text
  commit: ca42a55ddd5f3d9e866fe33b3b6862e9860f7604
  subdirs:
  - safe-coloured-text
- envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842

nix:
  packages:
    - zlib
