name: amqp-serialisation-gen
version: 0.0.0.0
github: "NorfairKing/amqp-client"
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2021 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - QuickCheck
    - amqp-serialisation
    - attoparsec
    - bytestring
    - genvalidity
    - genvalidity-bytestring
    - genvalidity-containers
    - genvalidity-sydtest
    - sydtest

tests:
  amqp-serialisation-test:
    main: Spec.hs
    build-tools: sydtest-discover
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - amqp-serialisation
    - amqp-serialisation-gen
    - attoparsec
    - bytestring
    - containers
    - genvalidity
    - genvalidity-bytestring
    - genvalidity-containers
    - genvalidity-sydtest
    - sydtest
