name: amqp-client
version: 0.0.0.0
github: "NorfairKing/amqp-client"
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - amqp-serialisation
    - attoparsec
    - bytestring
    - connection
    - network
    - unliftio

tests:
  amqp-client-test:
    main: Spec.hs
    build-tools: sydtest-discover
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amqp-client
    - amqp-serialisation
    - sydtest
    - sydtest-rabbitmq
